var dunkinDonuts = [
  [
    'assets/food_courts/dunkin_donuts/donut1.jpg',
    '',
    '\$22.5',
    '',
  ],
  [
    'assets/food_courts/dunkin_donuts/donut2.jpg',
    '',
    '\$22.5',
    '',
  ],
  [
    'assets/food_courts/dunkin_donuts/donut3.jpg',
    '',
    '\$22.5',
    '',
  ],
  [
    'assets/food_courts/dunkin_donuts/donut4.jpg',
    '',
    '\$22.5',
    '',
  ],
  [
    'assets/food_courts/dunkin_donuts/donut5.jpg',
    '',
    '\$22.5',
    '',
  ],
];
